name: Robot Framework CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # ✅ DO NOT use 3.1 – it will fail

    - name: Install dependencies
      run: |
        pip install robotframework
        pip install robotframework-seleniumlibrary
        pip install webdrivermanager
        webdrivermanager chrome --linkpath /usr/local/bin

    - name: Run Robot Tests
      run: |
        robot tests/
